web:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./docker/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    - .:/code
  links:
    - php:php
php:
  ports:
    - "9001:9001"
  build: ./
  # command: php artisan migrate
  # image: blood/php
  volumes:
    - ./docker/php.conf:/usr/local/etc/php-fpm.d/zzz.conf
    - .:/code
  external_links:
    - postgres
